// frontend/frontend-vue/src/views/Login.vue
<template>

    <div class="login">

        <h1>Mini Amazon</h1>

        <h2>Login</h2>

        <button
            @click="login"
            :disabled="loading"
        >

            {{ loading ? "Logging in..." : "Login" }}

        </button>

    </div>

</template>

<script setup>

import { ref } from "vue";

import { loginUser } from "../services/api";

const emit = defineEmits([
    "login"
]);

const loading = ref(false);

const login = async () => {

    try {

        loading.value = true;

        const response = await loginUser();

        localStorage.setItem(
            "token",
            response.data.token
        );

        emit("login");

    } catch (error) {

        console.log(error);

    } finally {

        loading.value = false;

    }

};

</script>

// frontend/frontend-react/src/pages/Login.jsx
import { useState } from "react";
import { loginUser } from "../services/api";

function Login({ setLoggedIn }) {

    const [loading, setLoading] = useState(false);

    const handleLogin = async () => {

        try {

            setLoading(true);

            const response = await loginUser();

            localStorage.setItem(
                "token",
                response.data.token
            );

            setLoggedIn(true);

        } catch (error) {

            console.log(error);

        } finally {

            setLoading(false);

        }
    };

    return (
        <div className="login">

            <h1>Mini Amazon</h1>

            <h2>Login</h2>

            <button onClick={handleLogin}>
                {loading ? "Logging in..." : "Login"}
            </button>

        </div>
    );
}

export default Login;
