// frontend/frontend-react/src/components/ProductCard.jsx
function ProductCard({ product }) {

    return (
        <div className="product-card">

            <img
                src={product.image}
                alt={product.name}
            />

            <h3>{product.name}</h3>

            <p>{product.category}</p>

            <h4>₹{product.price}</h4>

            <button>
                Add to Cart
            </button>

        </div>
    );
}

export default ProductCard;

// frontend/frontend-vue/src/components/ProductCard.vue
<template>

    <div class="product-card">

        <img
            :src="product.image"
            :alt="product.name"
        />

        <h3>
            {{ product.name }}
        </h3>

        <p>
            {{ product.category }}
        </p>

        <h4>
            ₹{{ product.price }}
        </h4>

        <button>
            Add to Cart
        </button>

    </div>

</template>

<script setup>

defineProps({
    product: Object
});

</script>
