// frontend/frontend-react/src/components/SearchBar.jsx
function SearchBar({ search, setSearch }) {

    return (
        <input
            type="text"
            placeholder="Search products..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
        />
    );
}

export default SearchBar;


// Explanation

// The parent component gives:

// search
// setSearch

// The input updates the search value.

// For example:

// Search: phone

// The dashboard can then display only products containing "phone".

// frontend/frontend-vue/src/components/SearchBar.vue
<template>

    <input
        type="text"
        placeholder="Search products..."
        :value="search"
        @input="updateSearch"
    />

</template>

<script setup>

defineProps({
    search: String
});

const emit = defineEmits(["update:search"]);

const updateSearch = (event) => { emit("update:search", event.target.value ); };

</script>


<!-- How SearchBar Works Dashboard sends the search value: -->

<SearchBar :search="search" @update:search="search = $event" />

<!-- When the user enters: iphone - the value becomes: search = "iphone";

Then Dashboard filters the products. -->
